name: Go Test on Pull Request

# Trigger this workflow on pull requests
on: 
  pull_request:
    branches:
      - 'main'   # This means the workflow will run on PRs for all branches

jobs:
  test:
    name: Run Go Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: ['1.21', '1.22', '1.23']  # Define Go versions to test against

    steps:
      # Checkout the code from the repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Go environment for each version in the matrix
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}  # Use the version from the matrix

      # Run `go test`
      - name: Run tests
        run: go test -v ./...
